name:                pfp-final
version:             0.1.0.0
github:              "YCLTW1995/pfp-final"
license:             BSD3
author:              "Yung-Ching, Lin"
maintainer:          "yl4337@columbia.edu"
copyright:           "2020 PFP Final Project"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/YCLTW1995/pfp-final#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src

executables:
  pfp-final-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - pfp-final

tests:
  pfp-final-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - pfp-final
